echo 请确保你已经使用npm 安装了 全局的protobufjs模块，并能在任意命令行窗口使用pbjs 命令。请在任意命令行数pbjs -help来确认。

echo 开始编译proto文件
%~d0
cd %~p0

rem The following adds the paths of both tf.exe and MsBuild.exe.
set PATH="D:\Microsoft Visual Studio 10.0\Common7\IDE";C:\Windows\Microsoft.NET\Framework\v4.0.30319;%PATH%

rem automatically check out files that generated by Google Protocol buffer.

set sourcedir=%~dp0
set uibot_common_proto_file_dir=%~dp0..\..\..\..\..\..\RobotFramework\RobotImgAppKit\AppProtocolBuffer\UIBotCommonProtocol\proto
set proto_file_dir=%~dp0..\..\..\..\..\uHOR-BE\uHORDemoProtocol

pbjs -t static-module -w commonjs -o %sourcedir%/uhor_planning_common.js %uibot_common_proto_file_dir%\uibot_common_protocol.proto %proto_file_dir%\uibot_uhor_common_enum.proto %proto_file_dir%\uibot_uhor_common.proto

echo  结束.
pause